name: Working device
description: Report a new working device
title: New working device
labels: ["working device"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report!
  - type: input
    id: device-manufacturer
    attributes:
      label: Please enter the name of the device manufacturer
      description: Tell us the device manufacturer
      placeholder: enter device manufacturer!
    validations:
      required: true
  - type: input
    id: device-type
    attributes:
      label: Please enter the device type
      description: Also tell us the device type
      placeholder: enter device type!
    validations:
      required: true
